# Generated by Django 3.2 on 2021-04-30 13:18

import django.contrib.postgres.fields
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0014_auto_20160504_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=8)),
                ('date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('document', models.JSONField()),
                ('structure', models.JSONField()),
            ],
            options={
                'unique_together': {('name', 'title', 'date')},
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('label', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), size=None)),
                ('content', models.TextField()),
                ('parent', models.JSONField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regcore.part')),
            ],
            options={
                'unique_together': {('label', 'part')},
            },
        ),
    ]
