# Generated by Django 3.2 on 2021-04-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0015_auto_20210423_1607'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('name', 'title', 'date')},
        ),
    ]
