# Generated by Django 3.2 on 2021-04-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0016_alter_part_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regcore.part')),
            ],
            options={
                'unique_together': {('label', 'part')},
            },
        ),
    ]
