# Generated by Django 3.2 on 2021-04-30 13:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0016_alter_searchindex_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchindex',
            name='label',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None),
        ),
    ]
